name: dashaun/jammy

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ARM64

    steps:
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: create-focal
        run: |
          docker build ./stack/focal -t dashaun/stack-build:tiny --target build --build-arg STACK_ID="io.paketo.stacks.tiny"
          docker push dashaun/stack-build:tiny
  
          docker build ./stack/focal -t dashaun/stack-run:tiny --target run --build-arg STACK_ID="io.paketo.stacks.tiny"
          docker push dashaun/stack-run:tiny

      - name: create-jammy
        run: |
          cd ./stack/jammy/build
          ./create.sh
          docker push dashaun/jammy-build:tiny
          cd ../run
          ./create.sh
          docker push dashaun/jammy-run:tiny