name: destroy-oci-arm64-runner

on:
  workflow_dispatch:

jobs:
  destroy-oci-arm64-runner:
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: paketo-arm64
      TF_CLOUD_ORGANIZATION: dashaun
    steps:

      - name: Checkout dynamic-tf-oci-arm64
        uses: actions/checkout@v2
        with:
          repository: dashaun/dynamic-tf-oci-arm64-runner
          ref: main